// v0.1 시연용 점심 메뉴 mock 풀 (16종).
// 각 메뉴는 (a) 호환 dietTags (b) 포함된 allergyTags (c) 적합한 healthTags 메타로
// 회원가입 입력값에 따라 분기 추천된다.

import type {
  AllergyTagKey,
  DietTagKey,
  HealthTagKey,
} from "@/lib/enums";

export type MenuMock = {
  id: string;
  name: string;
  merchant: string;
  walkMin: number;
  price: number;
  kcal: number;
  proteinG: number;
  diets: readonly DietTagKey[];
  allergens: readonly AllergyTagKey[];
  healthFit: readonly HealthTagKey[];
};

export const MENUS: readonly MenuMock[] = [
  {
    id: "m-chicken-salad",
    name: "닭가슴살 샐러드",
    merchant: "B카페 · 강남점",
    walkMin: 3,
    price: 9800,
    kcal: 420,
    proteinG: 32,
    diets: ["pesco", "omnivore"],
    allergens: [],
    healthFit: ["cholesterol", "blood-sugar", "fatigue"],
  },
  {
    id: "m-tofu-bibim",
    name: "두부 비빔밥",
    merchant: "한끼 · 강남점",
    walkMin: 5,
    price: 8500,
    kcal: 480,
    proteinG: 22,
    diets: ["vegetarian", "vegan", "pesco", "halal", "omnivore"],
    allergens: [],
    healthFit: ["cholesterol", "blood-sugar", "healthy"],
  },
  {
    id: "m-salmon-poke",
    name: "연어 포케",
    merchant: "포케하우스 · 역삼점",
    walkMin: 4,
    price: 11500,
    kcal: 520,
    proteinG: 28,
    diets: ["pesco", "omnivore"],
    allergens: [],
    healthFit: ["cholesterol", "hypertension", "fatigue"],
  },
  {
    id: "m-veg-curry",
    name: "야채 카레",
    merchant: "커리하우스 · 강남점",
    walkMin: 6,
    price: 9000,
    kcal: 560,
    proteinG: 14,
    diets: ["vegetarian", "vegan", "halal", "omnivore"],
    allergens: [],
    healthFit: ["healthy", "joints"],
  },
  {
    id: "m-shrimp-pad",
    name: "쉬림프 팟타이",
    merchant: "타이키친 · 선릉점",
    walkMin: 7,
    price: 12000,
    kcal: 640,
    proteinG: 24,
    diets: ["pesco", "omnivore"],
    allergens: ["shellfish"],
    healthFit: ["fatigue"],
  },
  {
    id: "m-beef-bulgogi",
    name: "소불고기 정식",
    merchant: "한식다움 · 강남점",
    walkMin: 5,
    price: 13500,
    kcal: 720,
    proteinG: 36,
    diets: ["omnivore", "halal"],
    allergens: [],
    healthFit: ["fatigue", "joints"],
  },
  {
    id: "m-acai-bowl",
    name: "아사이 너트 볼",
    merchant: "그릭브런치 · 압구정",
    walkMin: 8,
    price: 11800,
    kcal: 380,
    proteinG: 12,
    diets: ["vegetarian", "vegan", "pesco", "omnivore"],
    allergens: ["nuts"],
    healthFit: ["healthy", "blood-sugar"],
  },
  {
    id: "m-yogurt-bowl",
    name: "그릭요거트 볼",
    merchant: "그릭브런치 · 압구정",
    walkMin: 8,
    price: 8500,
    kcal: 320,
    proteinG: 18,
    diets: ["vegetarian", "pesco", "omnivore"],
    allergens: ["lactose"],
    healthFit: ["blood-sugar", "healthy"],
  },
  // === v0.2 확장: 16종까지 ===
  {
    id: "m-grilled-mackerel",
    name: "등푸른 생선구이 정식",
    merchant: "다정한밥상 · 강남점",
    walkMin: 4,
    price: 12500,
    kcal: 580,
    proteinG: 34,
    diets: ["pesco", "halal", "omnivore"],
    allergens: [],
    healthFit: ["cholesterol", "hypertension", "joints"],
  },
  {
    id: "m-low-sodium-chicken",
    name: "저염 닭갈비 정식",
    merchant: "한식다움 · 강남점",
    walkMin: 5,
    price: 11000,
    kcal: 590,
    proteinG: 30,
    diets: ["halal", "omnivore"],
    allergens: [],
    healthFit: ["hypertension", "fatigue"],
  },
  {
    id: "m-tomato-pasta",
    name: "토마토 페투치네",
    merchant: "Pasta Bar · 역삼점",
    walkMin: 6,
    price: 10800,
    kcal: 540,
    proteinG: 16,
    diets: ["vegetarian", "pesco", "omnivore"],
    allergens: [],
    healthFit: ["hypertension", "healthy"],
  },
  {
    id: "m-whole-wheat-sandwich",
    name: "통밀 햄에그 샌드위치",
    merchant: "에그스탠드 · 강남점",
    walkMin: 3,
    price: 7800,
    kcal: 440,
    proteinG: 21,
    diets: ["pesco", "omnivore"],
    allergens: ["lactose"],
    healthFit: ["blood-sugar", "fatigue"],
  },
  {
    id: "m-eel-rice",
    name: "장어덮밥",
    merchant: "장어한정 · 선릉점",
    walkMin: 9,
    price: 16500,
    kcal: 700,
    proteinG: 38,
    diets: ["pesco", "omnivore"],
    allergens: [],
    healthFit: ["fatigue", "joints"],
  },
  {
    id: "m-bone-soup",
    name: "사골 우거지 국밥",
    merchant: "할매국밥 · 강남점",
    walkMin: 4,
    price: 9500,
    kcal: 520,
    proteinG: 28,
    diets: ["omnivore", "halal"],
    allergens: [],
    healthFit: ["joints", "fatigue"],
  },
  {
    id: "m-quinoa-grain-bowl",
    name: "케일·퀴노아 그레인볼",
    merchant: "그린먼치 · 강남점",
    walkMin: 5,
    price: 11200,
    kcal: 430,
    proteinG: 20,
    diets: ["vegetarian", "vegan", "pesco", "omnivore"],
    allergens: [],
    healthFit: ["cholesterol", "blood-sugar", "healthy"],
  },
  {
    id: "m-hummus-plate",
    name: "후무스 플레이트",
    merchant: "지중해식탁 · 압구정",
    walkMin: 7,
    price: 10500,
    kcal: 460,
    proteinG: 18,
    diets: ["vegetarian", "vegan", "halal", "omnivore"],
    allergens: [],
    healthFit: ["cholesterol", "hypertension", "healthy"],
  },
] as const;

export function findMenuById(id: string): MenuMock | undefined {
  return MENUS.find((m) => m.id === id);
}
